# Generated by Django 2.2.6 on 2019-11-25 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191125_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='like_genres',
            field=models.ManyToManyField(blank=True, related_name='like_users', to='movies.Genre'),
        ),
    ]
