# Generated by Django 2.2.6 on 2019-11-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20191127_0424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sort2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hashtags', models.ManyToManyField(blank=True, related_name='sort2', to='movies.HashTag')),
            ],
        ),
        migrations.CreateModel(
            name='Sort1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hashtags', models.ManyToManyField(blank=True, related_name='sort1', to='movies.HashTag')),
            ],
        ),
    ]
