# Generated by Django 2.2.6 on 2019-11-25 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='open_year',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
