# Generated by Django 2.2.6 on 2019-11-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_sort1_sort2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('hashtags', models.ManyToManyField(blank=True, related_name='sorted_name', to='movies.HashTag')),
            ],
        ),
        migrations.RemoveField(
            model_name='sort2',
            name='hashtags',
        ),
        migrations.DeleteModel(
            name='Sort1',
        ),
        migrations.DeleteModel(
            name='Sort2',
        ),
    ]
